# ===============================================
# 1. Create the Namespace Resource
# ===============================================
apiVersion: v1
kind: Namespace
metadata:
  name: test-environment          # This explicitly provisions the 'vto' namespace in AKS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: test-environment  # <-- Added this line
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: gauravohra/cicdtest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP